### ISSUE TITLE
Se renseigner pour la couleur des poubelles

### ISSUE THREAD

**Issue by Hurlu** [Hurlu/NumerikDaysTrashSort#12]

**Comment by Aedanc** [comment]
Poubelles pour les déchets courants

Verte : le verre va dans la poubelle verte (facile à retenir). Il ne doit pas y avoir de bouchons ou couvercles sur les objets que vous jetez.

Jaune : la poubelle jaune accepte le plastique, le carton et le papier (s’il n’y a pas de poubelle bleue). Vous pouvez laisser les bouchons des bouteilles plastiques. Encore mieux, vous pouvez les donner à une association caritative comme Bouchons d’amour.

Bleue : la poubelle bleue est moins commune. On y met généralement le papier, les journaux, les annuaires, les prospectus, etc.

Grise/Noire : il s’agit de la poubelle “classique”. Elle sert à collecter le reste des déchets qui ne conviennent pas aux autres compartiments.

**Comment by Aedanc** [comment]
Pour les poubelles je propose:

Une verte pour le vert,
Une Jaune pour le plastique, le carton, le papier
Une marron pour le biodégradable
Une noire pour le reste
